services:
  - type: web
    name: recipe-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 8080
      - key: AIzaSyBFFZGYkqpn2f2LiGCtTDFDEdBSwiSAnI4
        sync: false 